### ISSUE TITLE
Adding / renaming stations during playback

### ISSUE THREAD

**Issue by ralxxx** [y20k/transistor#164] opened 2018-02-03 10:05 UTC
Thanks for all the work on transistor. I really enjoy it. Just one thing: 
I came across an issue with v3.0.0 when entering new radio stations.
Example: When you enter 2 stations (named "radio1" and "radio2"). Once you rename "radio2" with a name that it appears in the list above "radio1" (for instance "alpha") and click on it. The radio player shows in the bottom line that you clicked on "radio1".  Once you close the app the bug is gone.
I hope was clear. 
Have a nice weekend, Ralph

**Comment by y20k** [comment] 2018-02-07 14:14
Okay thanks for the hint! I will try to eliminate this bug.

**Comment by ralxxx** [comment] 2018-02-11 10:33
Hi. I am using the latest version of Transitor now (3.0.2). The bug has changed slightly its appearance but there is still an issue with radio stations that are being renamed.

Example:
- A new radio station is added. It name is "bevrtklara" ( just an example).
- I manually change the name to "vrt klara".
- When I now try to click the stations' name to play the radio stream, the name is changed back to its original. Only when I close the app and restart it, the new name will be adopted. 
Cheers, R.

**Comment by y20k** [comment] 2018-02-12 13:32
Thanks for providing the exact steps to reproduce this issue. That is very helpful!! BUT: on my test device a new (and old) station keeps the new name when I start playback after a rename. I have a few questions...

1. Did you maybe leave a step out in your description?
2. Did you  start playback via the play button or via long press in the list
3. how does the station name in the notification behave?
4. Does the issue only effect newly added stations, or can you reproduce it with "old" stations, too?

THX for helping here!!

**Comment by ralxxx** [comment] 2018-02-12 14:14
Hm, I tested it five or six times before I sent my initial post.
Now, I am not able to repoduce it in the same regular manner.
I'll get back asap.

**Comment by ralxxx** [comment] 2018-02-12 16:55
Anwers behind your question 
    Did you maybe leave a step out in your description? NO
    Did you start playback via the play button or via long press in the list. ONLY LONG PRESS
    how does the station name in the notification behave? SHOWS THE CORRECT STATION NAME
    Does the issue only effect newly added stations, or can you reproduce it with "old" stations, too? 
    DOESN'T MAKE A DIFERENCE

But there is another issue when adding a new station - sometimes a second instace of Transistor is opened.
I break down my observations to three scenarios:

SCENARIO 1
+++ I usually add radiostreams via a list of stream links that I send to myself by email (m3u).
+++ I usually change station names in a way that the station gets to a new posistion in my station list +++ So I change especially the first letter of its name
- Transistor is closed
- Open Transistor
- Start any stream
- Switch to email, click on a link and confirm to open it with Transitor 
- Now I can perfectly change the new stations name. No problem with that BUT Transitor has been opened in a second instance on my phone!!! 

SCENARIO 2
+++ like scenario 1 but no playing stream when adding a new station +++
- No second instance of Transistor is being opened, I can perfectly rename the new station.

SCENARIO 3
- I add a new station to Transistor (It can be one that was previously added and erased).
- I long-click on it to start the stream
- I rename it
- I long-click on the station
Now the stream stops (Transistor indicates that the stream was stopped), the stations is renamed back to its original name and switches back to the old position in the list of radio streams. 
- When I close the app and restart it the station appears with the changed name.
Can you reproduce my observations?

**Comment by y20k** [comment] 2018-02-12 17:33
I can reproduce at least SCENARIO 3. 👍 

SCENARIO 1: I experienced that problem (new instance of Transistor) on a phone running Android 4.4. Which version of Android did you test this on?

**Comment by ralxxx** [comment] 2018-02-12 18:01
Android 7.1.2/MIUI9.2

**Comment by maszek** [comment] 2020-02-17 11:29
I am using Transistor on Android 9 Pie and I am also experiencing this problem. The app appears to store renamed **names** and **icons** only occasionally after a couple of attempts. I don't know how to do it right. 
Changing the names and icons of the stations is quite important because it will help me identify the stations I've stored, which I cannot do by partial URL such as: http://www.radio-browser.info/web..
I'd like to point out that I installed it on a smartphone that is quite clean (freshly installed OS).

**Comment by mmmmna** [comment] 2020-05-06 15:53
I've seen similar problems. LG VK815 tablet without cell connections (only using WiFi). Tablet has Android 6, and it is cluttered with remnants of maybe 4 dozen uninstalled apps.
I create a new station, press play, title of station becomes 'listen'.
While playing, it is listed in the tray on the bottom of your app, as 'listen'.
Pull up the bottom tray.
Press the 3 dots, chose rename.
Switch to web browser, copy text from web page, switch back to transistor, paste the text as name.
Press rename button to accept the new text as name.

From here, I've seen 3 issues.
1) new name ignored, station list still shows 'listen' as the name.
2) infrequently, I'll have a twin of this entry - 2 entries, same link, both say 'listen'. I've even seen the station be renamed and the twin is not renamed.
3) everything appears to have committed properly, but when I long press to play a different station when playing the first station (the station which I renamed), the renamed station reverts back to 'listen'.

I'm pretty sure of these events, but they do not repeat with any consistency.

**Comment by mmmmna** [comment] 2020-05-07 02:21
Ok, update for my input... Very consistently failed to update the station name while the station was playing. I then stopped playing the station and once more renamed the station, this time the change held.

Otherwise, I like simple. This is. 😁

**Comment by y20k** [comment] 2020-05-08 19:06
@mmmmna I am currently re-writing the whole app (see #251). The display bugs should be fixed as soon as it is released - which still may take some time - they say that the last 5% of a project like this take the longest. :-)

**Comment by mmmmna** [comment] 2020-05-12 15:49
Thank YOU!!

**Comment by y20k** [comment] 2020-07-03 14:50
the issue should be fixed with the release of [Transistor v4](https://github.com/y20k/transistor/releases/tag/v4.0.0)

**Closed by y20k** 2020-07-03 14:50 UTC
Labels: bug
