### ISSUE TITLE
Bit Rate In The Info Screen

### ISSUE THREAD

**Issue by FionaHagen** [y20k/transistor#121] opened 2017-04-19 12:32 UTC
Hi, what do you think of adding information about the [bit rate](https://en.wikipedia.org/wiki/Bit_rate) in the info screen?
![bitrate](https://cloud.githubusercontent.com/assets/22400585/25180054/c31bb506-250c-11e7-9d06-69ee2af20a2f.jpg)

**Comment by y20k** [comment] 2017-04-20 09:35
Bitrate seems to be an interesting additional information for the info sheet (which it is still mostly empty). VLC (on desktop) has the folloing info in its **Codec Details** screen:

* Codec
* Channels
* Sample rate
* Bitrate

I need to check how easy this information is to extract from an active ExoPlayer. I'll report my findings here and decide then if it is worth the effort to implement it.

Thanks for the suggestion in any case!

**Comment by y20k** [comment] 2017-04-20 14:39
![stream-information](https://cloud.githubusercontent.com/assets/9103935/25236108/4e2ea8e4-25e7-11e7-8d7c-de63a93f5a89.png)

Extracting the bitrate does **not** work yet. But I gut success (see screen shot) on the following metadata:
* MIME type
* Channels
* Sample rate

I will further investigate. Priority for the next update has issue #120 though.

**Comment by FionaHagen** [comment] 2017-04-20 20:51
Thanks for your investigation 👍

**Comment by y20k** [comment] 2017-05-08 13:41
![more-metadata](https://cloud.githubusercontent.com/assets/9103935/25806685/580e9e0c-3404-11e7-95ec-28032cf04694.jpg)

A short update: Extended metadata display is coming along nice - no bitrate yet. I'll post further updates.

**Comment by y20k** [comment] 2017-05-15 12:52
Note to self. I tried several ways to get the bitrate from the running stream. The results:
* [`onTracksChanged`](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ExoPlayer.EventListener.html#onTracksChanged-com.google.android.exoplayer2.source.TrackGroupArray-com.google.android.exoplayer2.trackselection.TrackSelectionArray-) **-> Result = -1**
* [`onBandwidthSample`](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/upstream/BandwidthMeter.EventListener.html#onBandwidthSample-int-long-long-) **-> Result = method does not get called**
* [`onAudioInputFormatChanged`](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/audio/AudioRendererEventListener.html#onAudioInputFormatChanged-com.google.android.exoplayer2.Format-) **-> Result = -1**

So at the moment I do not see a way to get the bitrate with the help of ExoPlayer classes/methods. I could try to compute the bitrate myself, but that seems to be way too much work for that feature.

As a result the next version of Transistor will have a bit more stuff in the info sheet, but bitrate will be missing. I will leave this issue open (but un-assigned) for a while. Maybe I (or someone else) have a fresh idea in the next couple of weeks.

**Comment by FionaHagen** [comment] 2017-05-21 12:28
Thank you so much for your update @y20k! 😎

**Comment by y20k** [comment] 2017-07-17 07:41
> So at the moment I do not see a way to get the bitrate with the help of ExoPlayer classes/methods.

I am closing this issue since I do not know how to get the bit rate from the stream without computing it myself. But I will keep a reference to this in the [Previous discussions and feature requests](https://github.com/y20k/transistor/issues/48) list. Maybe someone has an idea.

**Comment by FionaHagen** [comment] 2017-07-19 21:03
Do you have an idea @ojw28?

**Comment by ojw28** [comment] 2017-07-19 21:50
We only expose bitrate information in cases where it's explicitly provided to us either in a manifest file (for DASH, SmoothStreaming and HLS adaptive playbacks), or in the media container (although there are likely cases where we could propagate the bitrate but don't in this case).

**Comment by FionaHagen** [comment] 2017-07-21 07:36
OK, thanks for your input @ojw28 🙂

**Comment by CodingFrieda** [comment] 2017-10-03 17:54
What do you think of adding the [label:hacktoberfest](https://hacktoberfest.digitalocean.com/) @y20k?

**Comment by y20k** [comment] 2017-10-06 14:33
Good idea. Lets give it a try. Thanks.

**Comment by y20k** [comment] 2017-11-06 12:56
hacktoberfest did not help here. I am closing this issue again. It will remain in [Previous discussions and feature requests](https://github.com/y20k/transistor/issues/48).

**Comment by VladimirMi** [comment] 2017-12-14 17:28
Hi @y20k!
You could extract the bitrate from the headers if the stream uses ICY or Icecast protocol.
Considering #136, you can take more information from them, such as the station url and genres, for display on the "Now Playing" screen.
More details [there](https://cast.readme.io/v1.0/docs/icy). I hope this helps.

**Comment by y20k** [comment] 2017-12-18 12:03
Hi @VladimirMi 

that is a very good approach. Thank you! I will look into it.

**Comment by Cormak** [comment] 2017-12-23 06:32
@VladimirMi Thanks for helping with this issue. This is the final piece of the puzzle for the info screen.

**Comment by Riotous** [comment] 2018-08-10 07:46
@y20k any progress on this? Bitrate is one of the most useful parts of any info display.

**Comment by y20k** [comment] 2018-08-10 19:59
@Riotous 

> Bitrate is one of the most useful parts of any info display.

I agree. Bitrate was the reason to implement the info sheet in the first place. But to be honest I haven't been working on this issue in quite some time. I do not have enough time to spare at the moment.

I mainly built Transistor to meet my own needs. Namely a free and lightweight way to listen to web radio. I use Transistor very often, but I rarely feel the urge to see what bitrate the current stream has. (You are still right: It should be part of the info sheet) Anyway: This and the fact that I do not have a lot of time between job, commute and family prevented me from working on this issue and other issues like this: Meaning new features that do not directly address my personal needs ;-).

Anyway the issue is still open. Marked with "help wanted". I do not want to rule out the possibility that I am going to tackle this issue in the future. And maybe someone else will step to help us out here.

But right now I am packing my bags for a longer summer vacation. Yay.
:beach_umbrella:

**Comment by y20k** [comment] 2020-07-03 14:47
This is a long standing feature request. In the meantime I rewrote the whole app (see #251). The new [version](https://github.com/y20k/transistor/releases/tag/v4.0.0) of Transistor does not feature any audio codec information anymore. 

I have no plans at the moment to bring it back.

<a href="https://raw.githubusercontent.com/y20k/transistor/v4.0.0/metadata/en-US/phoneScreenshots/03-player-sheet-oneplus5.png"><img src="https://raw.githubusercontent.com/y20k/transistor/v4.0.0/metadata/en-US/phoneScreenshots/03-player-sheet-oneplus5.png" width="360" /></a>

**Closed by y20k** 2020-07-03 14:47 UTC
Labels: enhancement, help wanted

**Comment by Long-FA** [comment] 2021-11-23 17:21
You can pull bitrate info from Radio-Browser API. Although from what i can see, this bitrate info is set manually and many of them are incorrect because station editing is not allowed at the moment.
https://de1.api.radio-browser.info/
