### ISSUE TITLE
Transistor does not add certain m3u links

### ISSUE THREAD

**Issue by Cormak** [y20k/transistor#55] opened 2016-02-12 22:02 UTC
Here's an example: http://www.listenlive.eu/rte1.m3u

When adding the aforementioned link to Transistor, it will simply say "download started" but nothing will actually play or get added to the list of stations.

Meanwhile, when I add the link to VLC for Android, it adds the link to the streaming playlist and will play it immediately upon tapping it. 

Transistor should be able to play any link ending with .m3u. What's going on here?

**Comment by y20k** [comment] 2016-02-13 07:10
Hi there,

Transistor right now does not detect write errors. That will change with the next version. 

Your case looks like a (undetected) write error to me. I cannot reproduce it though. That makes it hard to debug. 

My suspicion is that the call (getExternalFilesDir) that gets the path to the external storage directory (/Android/data/org.y20k.transistor/Collection) does not work reliably on some devices. I guess that could be Samsung phones with a micro sd-card - judging from a previous bug report. What kind of phone do you use?

Best wishes

**Comment by Cormak** [comment] 2016-02-13 16:17
I use a Moto X 2015 Pure Edition.

**Comment by y20k** [comment] 2016-02-13 20:23
Mmmh. No SD card. Then I was on the wrong track. My wife has a Moto X 2014. I can add the station you mentioned without any problems. :-( It is pretty hard for me to debug this without any error log. 

Did you try to add the raw streaming URL from within the m3u file (http://icecast2.rte.ie/radio1)? 

You can also try to download the m3u and place it manually into the  external storage directory (/Android/data/org.y20k.transistor/Collection).

The only thing I can further suggest: Please try out the next version of Transistor (probably next weekend, not sure yet). You will still not be able to add the particular station, but there will be an error message. Maybe you can then post a screen-shot of that message here. I would really appreciate that.

**Comment by Cormak** [comment] 2016-02-14 19:47
I tried that raw streaming URL and the same thing happens but adding the m3u file manually to the collection folder does indeed work. It shows up in the list when i open up Transistor and plays just as expected. I will definitely help you out with the next version as soon as I see it on the Play Store.

**Comment by y20k** [comment] 2016-02-15 07:44
:+1:

**Comment by y20k** [comment] 2016-02-19 16:21
[Version 1.2.3](https://github.com/y20k/transistor/releases/tag/v1.2.3) did fix at least one problem with saving to sd-card a user reported. Let's hope your problem was fixed too.

**Comment by Cormak** [comment] 2016-02-21 07:00
@y20k Got 1.2.3 and yep, the problem has been fixed. Links now open properly when tapped from other apps as well as when they are pasted into the app. 

One minor issue, though. When pasting the URL into the app,there is no longer a toast notification that says "download started". There is simply a short 2-3 second delay and the station just appears in the list. While it does work as it should, the "download started" notification was a good visual indicator that my pasted link was being processed. Perhaps bring that back?

**Comment by y20k** [comment] 2016-02-21 08:05
> "download started" notification [...] Perhaps bring that back?

Oh. I guess that notification somehow fell under the table. I will look into it.

**Comment by meonwax** [comment] 2016-02-21 19:42
My suggestion is:

As soon as the user ads a new station, temporaryly add a blank entry in the list showing a *spinner*-indicator to signal the downloading and importing process.
Therby the user would get a more explicit feedback that a process is currently ongoing in the background.
As soon as the import has finished, the entry could be replaced with the real new station entry.

**Comment by y20k** [comment] 2016-02-22 08:00
@Cormak:
> no longer a toast notification that says "download started"

That should be fixed in the next release. ([see commit](https://github.com/y20k/transistor/commit/a1c5b055b6652f974f55cdef34e6455da4ab3ba8))

**Comment by y20k** [comment] 2016-02-22 10:27
@meonwax 
I am undecided, if like your idea. On the one hand it would undoubtedly look very cool. On the one hand I think I would be a bit over visually the top compared to the rest of the app. 

I would rather like to see improvements in the Player screen. The animation there is a bit half baked. And conceptually speaking playback is the most important thing for Transistor. The use of animation should reflect this.

On thing I do not like about the process of adding is that on longer lists the newly added station is often hidden. Transistor should set the list view to the newly added station.

**Comment by y20k** [comment] 2016-02-22 10:29
I will close this issue because the main problem has been resolved. I / we should consider opening a new issue: Improve the workflow for "add new station".

**Closed by y20k** 2016-02-22 10:29 UTC
Labels: bug, help wanted
