### ISSUE TITLE
Allow changing stations with Next/Previous media buttons

### ISSUE THREAD

**Issue by c00ller** [y20k/transistor#89] opened 2016-06-06 03:22 UTC
I would like for an easy way to change stations while minimizing the interactions with my actual device, much like a physical AM/FM radio with pre-programmed stations. It would be nice to have an option to enable switching through stations by pressing the Next/Previous media buttons on a BT receiver or headphones with play/pause/next/previous media controls.

**Comment by y20k** [comment] 2016-06-06 14:37
Hi there,

First: Thanks for suggesting this. I need to think about this one for a while, before I make a decision

I did decide against a previous and next button in the main UI because I wanted to keep the App as simple as possible. I did also [decide against](
https://github.com/y20k/transistor/pull/46#issuecomment-181806863) those buttons in the notification, because I think that the notification should not have more capabilities than the app it was originated from.

Anyway. Nothing is set in stone. You request is similar but comes from a slightly different angle: 

**Controlling Transistor from another device (Remote Control)**

That would include Bluetooth, Android Wear, Headset Buttons. The programmatic foundation for remote control is [in part already there](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/PlayerService.java#L633). The app has no awareness yet what the "next" station would be. That I would have to implement. It would also be great if the app would announce a list of tracks/stations via a [MediaBrowserService](https://medium.com/google-developers/mediabrowserservicecompat-and-the-modern-media-playback-app-7959a5196d90#.3wgwuva28).

As I said, I need to think about it - and I need to look into it to see how much work that would be. 

Anybody else interested in this feature? Please leave note.

**Comment by c00ller** [comment] 2016-07-01 19:47
Even a simple implementation of Next/Previous cycling through the stations in alphabetical order (without any UI) would be greatly appreciated.

**Comment by y20k** [comment] 2016-07-01 20:09
Yeah. I will look into it. [MediaBrowserService](https://medium.com/google-developers/mediabrowserservicecompat-and-the-modern-media-playback-app-7959a5196d90#.3wgwuva28) should do the trick. Probably a mini-project for the next update. But as you said: no UI for this one for now - just Wear and BT.

**Comment by y20k** [comment] 2016-07-20 13:46
Hey @c00ller , 

bad news: I did try to implement the above mentioned MediaBrowserService, but I could not get it to work properly. I did try really hard ... invested several hours. But no results. I could not even get a MediaBrowser to connect properly to the Service. 

One problem was, that there was surprisingly few stuff to read on MediaBrowser. I guess I will give it a another try in a couple of month. But for now I will close this issue and reference it in [Previous discussions and feature requests](https://github.com/y20k/transistor/issues/48).

**Comment by y20k** [comment] 2017-11-06 12:57
hacktoberfest did not help here. I am closing this issue again. It will remain in [Previous discussions and feature requests](https://github.com/y20k/transistor/issues/48).

**Comment by rizapasha** [comment] 2018-04-06 00:07
i rethink that why someone has more than 3 stations is it they really hear it all a whole day? mine only have 2 stations, i hear it all. it is better to limit your only favorite radio station and stick with fewer.

the track skipping is against simplicity, simple live doesn't skip, simple live just flow it.

**Comment by y20k** [comment] 2018-06-07 18:39
Hi @rizapasha , track skipping is only available on Android Auto or on a Wear OS. The phone app remains as simple as it is now.

**Comment by y20k** [comment] 2018-06-07 18:43
Hi @c00ller ,

I got an interesting [pull request](https://github.com/y20k/transistor/pull/184) from @mook that implements track skipping on Android Auto. Do you have time to test it? Here is a signed APK of an upcoming version of Transitor. 

* [transistor-app-test-3.0.7-01.apk](https://www.dropbox.com/s/mcxhxe3ev1o7rv0/transistor-app-test-3.0.7-01.apk?dl=0)

**Comment by c00ller** [comment] 2018-06-07 18:44
@y20k I was just about to ask how soon I can test it 👍 Will try it today and let you know how it goes.

**Comment by y20k** [comment] 2018-06-07 20:47
Hi @c00ller ,

I am sorry. I am very time constrained at the moment. I only checked the validity of the code that @mook sent in. It should theoretically work. I did not test it with the Android Auto App.

@mook: do you have time to test why the solution is not working on Auto? I will try to do that too next week.

@c00ller hang in. We will get there.

**Comment by y20k** [comment] 2018-06-07 21:02
@mook if you find the time you might want to check out this https://developer.android.com/training/auto/audio/#required-actions

Maybe the fix is as easy as to set additional ACTIONS in PlayerService -> createSessionPlaybackState

Okay. Need to get up early tomorrow. I am out for today.

**Comment by y20k** [comment] 2018-06-08 13:50
Hi @c00ller,
the skip functionality is now exposed in the Android Auto app. @mook provided the necessary changes (see #185). I did a VERY brief test. It seems to work. Here is an updated and signed APK for further testing:
* [transistor-app-test-3.0.7-02.apk](https://www.dropbox.com/s/mpn1hpn7wtljkk0/transistor-app-test-3.0.7-02.apk?dl=0)

![screenshot_20180608-154149](https://user-images.githubusercontent.com/9103935/41161584-a4f85c1e-6b33-11e8-8b3e-8e918cacf208.png)

**Comment by c00ller** [comment] 2018-06-08 21:05
@y20k Good news - it works! Used it in my car, and steering wheel media controls worked as expected. SUCH a better (and safer) driving experience! 👍

**Comment by y20k** [comment] 2018-06-10 10:07
> I thought stations were ordered alphabetically. But in the Android Auto UI, the list of stations changed order somehow. 

@mook any idea what might have caused that?

**Comment by y20k** [comment] 2018-06-11 07:39
> Alternatively, sort the TreeMap by station name 

That sounds like the easier approach. Unifying the backend is a much bigger task that has do be tackled - but maybe not right now :-)

**Comment by y20k** [comment] 2018-06-11 09:59
A simple fix would be making the station name part of the station id string (see commit above), An okay solution?

**Comment by y20k** [comment] 2018-06-11 16:07
Here is a new development snapshot. The stations are now ordered alphabetically and stations do not start automatically when pressing prev/next if Transistor is paused (I think that is the expected behavior).

* [transistor-app-test-3.0.7-03.apk](https://www.dropbox.com/s/j2u4ns1rek2jhpr/transistor-app-test-3.0.7-03.apk?dl=0)

**Comment by c00ller** [comment] 2018-06-11 16:20
>  and stations do not start automatically when pressing prev/next if Transistor is paused (I think that is the expected behavior).

I think this is unexpected! Playing when pressing prev/next while paused is the behavior for the media apps I use (Google Play Music, Windows Media Player on PC, etc.).

**Comment by y20k** [comment] 2018-06-11 16:31
Okay. THX. Just to clarify. The expected behavior of the app is: 

* press next while paused --> switches station AND starts it

Right?

**Comment by c00ller** [comment] 2018-06-11 16:32
Yes, that's right 👍

**Comment by y20k** [comment] 2018-06-11 16:40
My idea was: What if you want to skip several stations ahead. Do you really want to have them  all started? Imagine a ten-station-skip.

**Comment by y20k** [comment] 2018-06-11 16:41
> is the behavior for the media apps I use (Google Play Music, Windows Media Player on PC, etc.).

I see. Spotify does that too. Maybe I should roll back the change :-)

**Comment by y20k** [comment] 2018-06-11 16:48
... now back to the previous skip behavior :-)
* [transistor-app-test-3.0.7-04.apk](https://www.dropbox.com/s/6r0ug2qvm49zt7o/transistor-app-test-3.0.7-04.apk?dl=0)

**Comment by y20k** [comment] 2018-06-13 13:31
Hi @c00ller 

> Ready for an official release IMO

I am not sure. **On the one hand** ...

* the skip feature works on Android Auto as expected :+1: 

... **on the other hand** the new feature introduced a few new issues. :-1: Mainly:

* the skip feature is offered on all media controlling devices not only on Auto, for example Wear OS and supported headphones will offer a skip option. But the feature does not work here. 
![screenshot_1528893549](https://user-images.githubusercontent.com/9103935/41352416-b41189fc-6f19-11e8-8170-8641028a2be3.png)

* less important: Changes to the station list - rename, delete, logo change - made on the phone are not reflected on Auto or Wear. That was the case before, too. But was less likely to stumble upon.

Both problems are more or less a result of the fact, that the remote control features were added after Transitor was basically finished. I did not take the time to re-architect the app. It now has internally two lists of stations - one for the phone and the other one for remote control devices like Auto and Wear. Changing the base architecture always seemed too much work, that is why I was always to reluctant in tackeling this issue here. 

Anyway. I am still glad and thankful that @mook stepped up and offered a solution based on the old hack with the two lists. At its core it is great and works flawlessly. But what should we do about the side-effects?

**Comment by y20k** [comment] 2018-06-13 14:09
> But what should we do about the side-effects?

... I could expose the skip feature only, if the app has detected `UI_MODE_TYPE_CAR` - if the app is connected to an Android Auto instance #thehackyway :-) I tried this, and it works with the Android Auto App. I will post an updated APK later.

> Ready for an official release IMO

Maybe if the latest changes turn out to not cause any new issues.

**Comment by y20k** [comment] 2018-06-13 17:39
Okay. Here as promised a version of Transistor that only exposes the skip feature if it detects Car Mode. It works as intended with the official Android Auto App (= showing skip controls) and with the Android Wear Emulator (not showing skip controls).

@c00ller: You have a car with built-in Android Auto? If so, can you check if the feature works? 

* [transistor-app-test-3.0.7-05.apk](https://www.dropbox.com/s/wy0p9ttfvfp8fif/transistor-app-test-3.0.7-05.apk?dl=0)

Thanks you guys for your help and patience! :smile:

**Comment by c00ller** [comment] 2018-06-13 20:10
@y20k Yes, my car has "built-in" Android Auto. To clarify, car-supported Android Auto is simply a projected display of the Android Auto app running on the phone. So AFAIK, any behavior in the Android Auto phone app should be identical to that in the car. 

So if I understand correctly, the latest test version will behave the same in Android Auto (from a user perspective) as the last test, just with some under the hood changes tailored for Wear OS? Just wondering exactly what I should be looking for when I plug in to my car.

**Comment by y20k** [comment] 2018-06-13 21:03
If everything STILL works as expected, that would be great. My only fear would be that the latest changes introduce regressions like disappearing skip buttons.

**Comment by c00ller** [comment] 2018-06-14 02:03
@y20k Everything looks good on my end for transistor-app-test-3.0.7-05.apk

**Comment by mook** [comment] 2018-06-14 04:14
This should probably go into a different issue, but as far as I can tell the prev/next buttons work fine when paired with a Wear OS device; I was testing this by making [the condition](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/PlayerService.java#L785) always return true.  That's with a physical phone paired with an emulated Oreo watch.

We don't need to resolve this right now, though; there's plenty of time to figure out what's going on :)

**Comment by y20k** [comment] 2018-06-14 12:57
> We don't need to resolve this right now

You are right @mook. I will publish a new version Transistor with the skip feature on Android Auto. Wear OS and other control-units can follow later.

> but as far as I can tell the prev/next buttons work fine when paired with a Wear OS device

For me Transistor kept crashing when I tried to control it via Wear Emulator and headphone buttons. I think - but I am not sure - that is because [onLoadChildren](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/PlayerService.java#L423) does not get called, if the app is only connected to Wear OS.

**Comment by y20k** [comment] 2018-06-15 20:02
New version is out. Closing this issue. :smile: 

* [v3.0.7](https://github.com/y20k/transistor/releases/tag/v3.0.7)

**Closed by y20k** 2018-06-15 20:02 UTC
Labels: enhancement, help wanted
