### ISSUE TITLE
AAC doesn't play

### ISSUE THREAD

**Issue by vinzv** [y20k/transistor#19] opened 2016-01-20 17:13 UTC
I can't play AAC streams like http://www.rockantenne.de/webradio/channels/classic-perlen.aac.pls
The mp3/m3u stream from the same source works fine. System is CM12.1.

**Comment by y20k** [comment] 2016-01-20 19:59
Thank you for the bug report. On my phone (Nexus 5, Android 6) the above mentioned AAC stream plays just fine. Where you able to add the station, did you already have problems with adding? If you have Android Studio running somewhere a System Log would be of interest for me. Best wishes.

**Comment by cbuctok** [comment] 2016-01-22 09:23
I have z3c and I can listen mp3 just fine.
I cannot say this about aac.

**Comment by y20k** [comment] 2016-01-22 09:51
Thanks for the feedback. How does the playback fail? Do you get an error message, or does it just not play the station? Do you too have a custom ROM?

**Comment by y20k** [comment] 2016-01-23 06:47
I tested the link you mentioned in an emulator. AAC playback started on Android 4.4.2 and on Android 5.1.1 without issues. On the other hand: A friend of mine with a CM phone cannot playback this station either. So the bug maybe related to CM?! Maybe a patent issue with the AAC codec? I need to dig into that further.

**Comment by vinzv** [comment] 2016-01-25 10:14
Meanwhile I switched back to official MIUI rom (4.4.4 based). The
problem exists here as well.

**Comment by y20k** [comment] 2016-01-25 13:09
Hi there. 

If your phone is rooted you could try to capture a [system log](http://forum.xda-developers.com/showthread.php?t=1726238). I am very curious. 

I understand that is maybe a bit much to ask. Especially since chances are low, that I am able to fix the problem, given the fact that I cannot reproduce the error on my phone and in an emulator.

**Comment by y20k** [comment] 2016-02-01 11:58
Closing this issue for now. I guess it is related to MediaPlayer and/or AAC patents. I do not plan to switch from MediaPlayer to another audio library - which seems to be the only solution to this problem. Sorry to disappoint you.

**Closed by y20k** 2016-02-01 11:58 UTC
Labels: wontfix

**Comment by y20k** [comment] 2017-06-11 21:07
By the way: AAC should work now. See #137.
