### ISSUE TITLE
the label of player_station_metadata fails to update when the station name was changed (fail to sync?)

### ISSUE THREAD

**Issue by tingsu** [y20k/transistor#249] opened 2020-03-03 14:05 UTC
- I have searched the history issue list, and have not found similar issues. 

- The issue was found in the latest release version 3.2.4 from Google Play (also exists in the latest master), and were reproduciable on both a Google Plxel 3 and an Android emulator 6.0 device.

- Bug description
When a station is playing, the label of player_station_metadata (a line of small text, locating underneath the station name) provides some additional info about which station is now playing. This function is perfect if I rename a non-playing station. However, if I rename the station while the station is playing, this label fail to sync with the new station name.

- Correct functionality

This video shows the correct behavior, i.e., the label of player_station_metadata  (``205-lo-mp3`` in this case) was indeed updated to ``my favorite`` (i.e., the new station name). Perfect!

![20200303_145157](https://user-images.githubusercontent.com/3156978/75782913-eb595d00-5d5f-11ea-9310-3420a9efb30c.gif)

- Incorrect functionality

This video shows the incorrect behavior i.e., the label of player_station_metadata  (``205-lo-mp3`` in this case) failed to be updated to ``my favorite``. A little annoying.

![20200303_145256](https://user-images.githubusercontent.com/3156978/75782926-ef857a80-5d5f-11ea-97b8-076c41ff8573.gif)

Hope my report can help fix this issue. Thanks! :)

**Comment by y20k** [comment] 2020-03-11 09:25
Hi @tingsu,

sorry for answering so late. I was pretty busy at work.

Thank you for this perfect bug report. The root cause for this bug is the same as the one behind the bugs you reported earlier (#234, #236, #239): Transistor has  problems with manipulating stations (rename, delete) while playback is running. This is due to the way Transistor stores its list of radio stations. 

I am currently rewriting the whole app from scratch. In the new version of Transistor the list of radio stations will be stored differently. Currently I am making good progress on this. I feel like I am half way through. But as always with those kinds of projects, the last 5 percent are the hardest. Plus: This is a hobby project. I can only work on it in my spare time.

Anyway. You work is not lost. I will use the bugs you found as test cases for the All-New-Transistor. I will probably not fix them for the current version.

**Comment by tingsu** [comment] 2020-03-11 11:21
Thanks for your reply and confirmation @y20k . You plan sounds great! I will continue to contribute testing your brand-new version when it is released. I am hoping to make these apps better :)

**Comment by oraluben** [comment] 2020-04-22 10:11
Hi @y20k , thanks to your Kotlin rewrite, we've confirmed #234, #236, #239 have been fixed! You should close those issues. And while this one seems remaining, could you please take a look again? Thanks!

**Comment by tingsu** [comment] 2020-04-22 10:23
Hi @y20k , we also checked #235, which was now also fixed in this Kotlin rewrite. Nice! Although at that time you think fixing this issue may need rewriting the architecture.

**Comment by y20k** [comment] 2020-04-22 19:10
Hi @tingsu & @oraluben , thanks for your tests! 

Please consider that the code I uploaded yesterday does not have release quality yet. I think a real first release will have to wait until the summer. The app still has a lot of little papercuts. Anyway. Given all that, I am really pleased that some issues are already solved! 

In the past I did only close issues, that are fixed in a stable release version. I think I will continue to do so here. Although it is really tempting to click on the Close button below. :smiley:

**Comment by y20k** [comment] 2020-04-22 20:00
> rewriting the architecture

Most changes happened "under the hood". For example: Transistor does not store each radio station in a m3u playlist file. Instead it writes all stations to single collection file. That change allowed me to store additional meta information for each station, which in turn enables things like updating stations, marking stations as starred. So really a lot did change, but most of it is not visible. But these changes hopefully put me in a position where bugs are easier to fix and new features are easier to implement. :crossed_fingers:

**Comment by tingsu** [comment] 2020-04-22 21:02
Thanks for your positive feedback and efforts on the rewriting. Yeah, your adjustments on the architecutre/design ease the bug fixing. If you do not bother, we will close the issue  #234, #236, #239?

**Comment by tingsu** [comment] 2020-04-24 07:48
Thanks for your reply. I would like to close these issues  (#234, #236, #239) and will leave a reminder there. I will keep this issue open so that we can still refer to these temporarily closed issues.

**Comment by y20k** [comment] 2020-07-03 13:51
should be fixed in the upcoming v4 version. thanks for the bug report. please re-open if it is still an issue.

**Closed by y20k** 2020-07-03 13:51 UTC
