### ISSUE TITLE
Transistor keeps running in the background even when not in use

### ISSUE THREAD

**Issue by Cormak** [y20k/transistor#159] opened 2017-12-12 12:25 UTC
Hi there, just noticed something in the 3.0.0.4 test apk. 

The playerservice keeps running in the background even when I'm not using the app and even when its not in my recents list. I was just looking at my currently running applications and it has been running for 77 hours straight. 

It would be great if Transistor would automatically close itself out completely when the window is not in use or the notification has been cleared away after like 30 min or so. I have 3GB of RAM and a good CPU on my phone but this could be useful for people with budget or older phones, even if Transistor doesn't use up that many resources to begin with.

**Comment by y20k** [comment] 2017-12-13 08:41
Hi.

Thanks for that observation! I will look deeper into this. 

As far I know that behavior is somewhat intended. I entrust the memory and resource management to the operating system. That is for example one of the reasons why Transistor does not have a [Quit Button (Issue 102) ](https://github.com/y20k/transistor/issues/102). 

A little background: Starting a service or a part of an app may use up way more resources than keeping the component in memory. During playback and as long as the notification is visible the service is running flagged as a so called "foreground service".

> A foreground service is a service that the user is actively aware of and is not a candidate for the system to kill when low on memory. A foreground service must provide a notification for the status bar (from: [Service](https://developer.android.com/guide/components/services.html#Foreground))

When a user swipes / dismisses the notification. Transistor drops the foreground flag. From that point on the operating system can do what it wants with the service. If you happen to have a lot of RAM it is probably more energy efficient to keep it in memory.

The thing I need to investigate ( = note to self) is: Maybe I can flag the service as destroyable a step sooner, meaning: as soon a user selects [STOP](https://speakerdeck.com/ianhanniballake/state-of-media-playback?slide=38). That may have repercussions on the notification.

**Comment by y20k** [comment] 2018-01-10 20:49
> The thing I need to investigate ( = note to self) is: Maybe I can flag the service as destroyable a step sooner, meaning: as soon a user selects STOP. That may have repercussions on the notification.

I looked into this and I was positively surprised by myself 🦊 (joke). It seems that Transistor's PlayerService is already modeled correctly - meaning: It works as intended. The flag that marks the service as destroyable is set as soon as a user presses STOP. In the UI that is indicated by the notification which is swipeable when Transistor is not playing music. From that point on it is up to the Android system to decide if it is better/efficient to kill the service or to keep it in memory.

I am not going to question the decisions that the Android memory management makes.  See the discussion about a [Quit Button](https://github.com/y20k/transistor/issues/102).

Do not be disappointed, but I am closing this issue for now.

**Closed by y20k** 2018-01-10 20:49 UTC

**Comment by Cormak** [comment] 2018-01-11 08:52
@y20k That's ok. If it looks alright to you, I can't really complain. I just wanted to know if you saw anything irregular.
