### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by vonglahn** [y20k/transistor#199] opened 2018-11-06 09:24 UTC
Hi there,

On my phone (Moto G6/Android 8.0) Transistor crashes sometimes when I press the play button. Not everytime but usualy in the morning. It workes on the second try.

Best Regards

**Comment by y20k** [comment] 2018-11-16 19:35
Hi there,

it took me a while to reproduce this issue. But now I know how.

1. in `Settings > Developer options` activate `Don't keep activities`
2. open Transistor and select a station but do not start playback
3. go to home screen (`Don't keep activities` will force quit transistor)
4. open Transistor and press play
5. Crash

Do not forget to turn off `Don't keep activities` since this option will drain your battery.

**Comment by y20k** [comment] 2018-11-19 14:40
This issue should be fixed with [v3.1.0](https://github.com/y20k/transistor/releases/tag/v3.1.0). Please re-open, if it still persists. THX

**Closed by y20k** 2018-11-19 14:40 UTC
Labels: bug
