### ISSUE TITLE
Takes more time to load radio stations

### ISSUE THREAD

**Issue by sumantimalsina9** [y20k/transistor#116] opened 2017-01-26 12:51 UTC
Everything is this project is good but I find the radio streaming takes longer than any radio players in the play store. Is there any solution?

**Comment by y20k** [comment] 2017-01-26 14:40
Hi there,

the startup time can vary from stream to stream. Is that your experience, too? Can you **post the address of an example stream**? It also varies from device to device a lot. I wonder how long your stream will take to load on my phone and/or in the emulator.

Transistor does not have a custom playback engine. It uses the official Android [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer.html) library. Other radio player probably use different audio libraries.

> Is there any solution?

Probably not. But lets see. 😄

**Comment by sumantimalsina9** [comment] 2017-01-27 03:12
For some stations it took more than 5 minutes to load. I am thinking to change the default media player to some  library like AAC decoder.
https://github.com/vbartacek/aacdecoder-android

Even though it is a great app with many features, the primary purpose of this app is to play radio. And I feel like there is still something missing because of the streaming time it takes to load the station.

**Comment by y20k** [comment] 2017-02-10 19:26
We had several discussions(*) here regarding better AAC support. For now I am still a bit reluctant to change the main audio engine. The only thing that helps, is to look for a MP3 version of your station - only if there is one though. Sorry.

(*)
https://github.com/y20k/transistor/issues/117
https://github.com/y20k/transistor/issues/90

**Comment by y20k** [comment] 2017-03-20 14:49
Hi @sumantimalsina9 ,

are you interested in testing a version of Transistor that uses a new media library ([ExoPlayer](https://developer.android.com/guide/topics/media/exoplayer.html))? This version speeds up the start-up time for AAC - at least on my devices.

If so, please head over to issue #120 and report your findings.

Thanks & take care.

**Comment by y20k** [comment] 2017-04-21 13:03
[v.2.2.1](https://github.com/y20k/transistor/releases/tag/v2.2.1) is out. It comes with the new playback library  `ExoPlayer`. I hope the issue is fixed. I will close this it for now. Feel free to reopen, if you still got problems.

**Closed by y20k** 2017-04-21 13:03 UTC
