### ISSUE TITLE
App loses bluetooth connection

### ISSUE THREAD

**Issue by mobybit** [y20k/transistor#88] opened 2016-06-01 15:41 UTC
I use a bluetooth speaker to listen to the streams via Transistor. Always after about 30 minutes the app stops to play the stream so I've to restart. 

Android 6.01
iTeufel Air Blue

**Comment by y20k** [comment] 2016-06-01 19:51
Hi there, 

Thank you for reporting this issue. I really need feedback like this to make Transistor better and more stable. I have a few questions:

> the app stops to play the stream

- How does that issue manifest itself in the UI. Is the notification still up? Does the UI still display a green indicator?

- Do you think the issue is related to Bluetooth, or does Transistor also stop its playback when connected via cable?

- Which version of Transistor do you use? Since [v2.0.2](https://github.com/y20k/transistor/releases/tag/v2.0.2) the app uses [startForeground](https://developer.android.com/reference/android/app/Service.html#startForeground%28int,%20android.app.Notification%29) to prevent the Android system to shut it down during playback. See pull request #85. With earlier versions I indeed had some reports that the app got killed by the system, if Android needed more memory.

**Comment by mobybit** [comment] 2016-06-01 20:27
Thanks for your answer.

Yes, the UI still display a green indicator. I have to restart the stream. I think this problem is related to bluetooth but I can test this. 
Before the connection breaks the stream "stutters" a little bit.

Transistor 2.0.2 but the problem exists in 2.0.1 too.

**Comment by y20k** [comment] 2016-06-06 14:02
Hi there,

> but I can test this. 

That would be great. 
If we could rule out Bluetooth as the cause of the problem, there are two possible causes left.

1. Playback service got killed by the memory management of the system
2. There is a problem with reconnecting to a failing stream - the mentioned "stutter" could be a hint here.

Please drop me a note if you can reproduce the bug without Bluetooth.

PS. I was AFK for the last couple of days. So please excuse my delayed response.

**Comment by mobybit** [comment] 2016-06-06 21:28
It's a wifi connectivity problem. Sometimes the stream breaks. So I think you're right with your second guess.

**Comment by y20k** [comment] 2016-06-07 15:23
Okay. Thanks for checking this. This problem came up before (#32 and #65). Transistor has a method to reconnect (#32) to a stream when the connection is lost. I'll look into it. Maybe the method can be improved.

In the meantime: If you know of a way to reproduce the behavior (Airplane-Mode on/off?), please let me know. That usually really speeds up bug fixing.

**Comment by mobybit** [comment] 2016-06-09 17:31
Maybe it sounds a little bit strange, but it seems I've these connection problems only with Transistor. My smartphone (Moto G3) is connected to a Fritzbox. No errors if Transistor isn't running (log). And no errors with other similar apps using streams (RadioDroid, AntennaPod)... Any idea? Thank you!

**Comment by y20k** [comment] 2016-06-09 19:37
I have no idea yet. But I will investigate this. My guess is either:
1. WiFi disconnect (Transistor does not use a wifilock)
2. stream gets restarted server-side (probably more likely)

> In the meantime: If you know of a way to reproduce the behavior (Airplane-Mode on/off?), please let me know. That usually really speeds up bug fixing.

That would really help. Is there a certain station that is especially troublesome?

**Comment by y20k** [comment] 2016-06-13 09:26
Hi there,

since I do not know what exactly caused your problem, I will go with a blind approach. Maybe this is working: I did add some code to restart the player if it encounters an error. This could very well end in an infinite loop. So I am not sure if I will stick with this code.

Are you interested in testing this solution? If so there is an APK for the upcoming version of Transistor: 
[transistor-app-testing-2.0.4a-on-error-reconnect.apk](https://www.dropbox.com/s/n95cdmo9g6d1msx/transistor-app-testing-2.0.4a-on-error-reconnect.apk?dl=0)

**Comment by mobybit** [comment] 2016-06-14 21:43
Okay, thank you, I will test it.

**Comment by y20k** [comment] 2016-07-13 09:38
I am closing this one for now. Feel free to re-open, if the issue is not resolved. Best regards.

**Closed by y20k** 2016-07-13 09:38 UTC
