### ISSUE TITLE
Crash on fast multiple clicks on Play/Stop button

### ISSUE THREAD

**Issue by calipzo** [y20k/transistor#149] opened 2017-08-30 11:38 UTC
Steps to reproduce:

1. Open App.
2. Add URL with stream.
3. Open station.
4. Do multiple **fast** clicks on Play/Stop button.

Tested on 3 real devices (Android 7, Android 7.1.1, Android 6) and official Android Emulator virtual device with Andorid 7.1.1. Tested on compiled latest source and at least 5 previous commits (plus Google Play version).

![device-2017-08-30-141904](https://user-images.githubusercontent.com/2325646/29870285-6de3be4e-8d8f-11e7-8b72-c4cbf36d5baf.gif)

Some logs:
`08-30 14:19:38.709 25337-25337/org.y20k.transistor E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: org.y20k.transistor, PID: 25337
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.SimpleExoPlayer.prepare(com.google.android.exoplayer2.source.MediaSource)' on a null object reference
                                                                         at org.y20k.transistor.PlayerService.preparePLayer(PlayerService.java:692)
                                                                         at org.y20k.transistor.PlayerService.access$900(PlayerService.java:105)
                                                                         at org.y20k.transistor.PlayerService$InitializePlayerHelper.onPostExecute(PlayerService.java:952)
                                                                         at org.y20k.transistor.PlayerService$InitializePlayerHelper.onPostExecute(PlayerService.java:908)
                                                                         at android.os.AsyncTask.finish(AsyncTask.java)
                                                                         at android.os.AsyncTask.access$500(AsyncTask.java)
                                                                         at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java)
                                                                         at android.os.Handler.dispatchMessage(Handler.java)
                                                                         at android.os.Looper.loop(Looper.java)
                                                                         at android.app.ActivityThread.main(ActivityThread.java)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
`

Sorry for my english.

**Comment by y20k** [comment] 2017-08-30 12:01
Thx. I will look into this.

**Comment by y20k** [comment] 2017-09-04 14:30
can you paste the link of the station that produced the crash on your system? thx

**Comment by calipzo** [comment] 2017-09-04 18:36
Please try this:
http://stream.radio.co/s4360dbc20/low

**Comment by y20k** [comment] 2017-09-11 08:34
Thanks. I cannot reproduce a crash on my device. But the Transistor UI becomes unresponsive when I rapidly tap on the play button. I guess your crash and the unresponsive UI are caused by the same problem. I think I know what to do change that.

**Comment by y20k** [comment] 2018-01-10 19:40
Transistor got a new user interface (see [v3.0.0](https://github.com/y20k/transistor/releases/tag/v3.0.0)). The old player screen is gone. So I guess I can close this issue for now. It is possible though that the new ui is plagued with the same bug. I cannot test it because the crash was not reproducible on my phone. :-( Sorry.

**Closed by y20k** 2018-01-10 19:40 UTC
Labels: bug
