### ISSUE TITLE
Renaming Station Fails

### ISSUE THREAD

**Issue by tehabe** [y20k/transistor#40] opened 2016-02-06 21:15 UTC
I'm trying to rename a station from _Deutschlandradio_ to _Deutschlandradio Kultur_ but after _Deutschlandradio_ nothing happens. It just stops, I can still type though.

**Comment by meonwax** [comment] 2016-02-06 23:38
I have already looked into this issue. Will provide a fix soon.

**Comment by y20k** [comment] 2016-02-07 06:54
Oh. A bug in the restriction of max possible number of characters. My five cents on this: you could crank up the max number quite a bit. The only limit may be the file system of the external storage, since station names and file names correspond. The UI shortens longer names automatically according to the screen size. Thanks for helping out on this one.

**Comment by meonwax** [comment] 2016-02-07 14:29
> The UI shortens longer names automatically according to the screen size

I saw this, you use an ellipsis on end of the string when too long.

Perhaps the filename should not necessarily correspond to the station name.
I think the station name will be written inside the created m3u file, so we can do something like the old fat16 file names, when we see much longer names. Just shorten the actual name on the external storage.

**Comment by y20k** [comment] 2016-02-07 17:22
I think if not necessary we should keep the link between filename and station name. It is such a simple solution. 

Or at least I think the decision should depend on the maximum number of characters the file system allows. If it is just 32 characters - we should go with your suggestion and cut the dependency. Anything from 64 and up should be enough  for a station name. 

In `/app/src/main/res/layout/list_item_collection.xml` the station name is shortened depending on the screen size. Station names could be 256 and higher. It will never break the layout.

On the input side: In `/app/src/main/res/layout/dialog_rename_station.xml` I did cut the station name at 16 characters. That is way(!) too short. I will definitely lift that in the next release.

**Comment by tehabe** [comment] 2016-02-07 17:50
IMHO you should rather limited a file name than an entry in a file, the latter can include characters which might be not possible on the file system.

**Comment by y20k** [comment] 2016-02-07 18:01
just for the discussion: https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits

**Comment by meonwax** [comment] 2016-02-07 18:33
> IMHO you should rather limited a file name than an entry in a file, the latter can include characters which might be not possible on the file system.

This is another argument for using a simple filename and storing the *title* inside the m3u.
> just for the discussion: https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits

Is there a way for determining of the filesystem type?

**Comment by y20k** [comment] 2016-02-07 20:04
The title is already stored inside the m3u. To clarify: I do not think that it is strictly necessary to have the file name mirror the station name. But it is convenient. 

If we would cut the link between the two we would need a method that can reliable produce and reproduce a filename (derived from the station name? or a hash?). The new solution then needs testing: There are some people already running the app on their phones (possible conflicts with the then old filenames?). Also the station images are stored using the same "formula". 

It is not a hard task to do all that. I just think it is not necessary (yet?). There are more fun things to do to improve the app. On the other hand. Do not feel discouraged. I will definitely not reject a solid solution for this issue!

> IMHO you should rather limited a file name than an entry in a file, the latter can include characters which might be not possible on the file system.
That is true. But there are actually not too many characters to worry about. Some of them are already being filtered out.

**Comment by meonwax** [comment] 2016-02-08 08:46
> There are more fun things to do to improve the app

Yes that's true. Therefore we are participating :)

I saw you just committed a quick fix extending the input field length. That should do the trick for the original issue.

**Comment by y20k** [comment] 2016-02-08 14:10
> That should do the trick for the original issue.

I hope so too. Will close this issue for now. Problem should be fixed in the next release.

**Closed by y20k** 2016-02-08 14:10 UTC
Labels: bug
