### ISSUE TITLE
multiple stations in one m3u

### ISSUE THREAD

**Issue by rlucassen2** [y20k/transistor#295] opened 2020-08-19 07:55 UTC
It would be nice if transistor could handle multiple stations from one m3u file, like the m3u's found here:

[http://radio.xaq.nl/](http://radio.xaq.nl/)

1) click the hamburger options menu (right upper corner)
2) choose "service"
3) choose "playlists" (hamburger icon with musical note)
4) choose one of the genres

If I enter such an m3u like [http://radio.xaq.nl/m3u/speech.m3u](http://radio.xaq.nl/m3u/speech.m3u) then transistor waits without timeout BTW. IIRC the older versions (a few years ago) would simply play the first entry. Could be due to a stream that cannot be handled, no idea.

Richard.

**Comment by y20k** [comment] 2020-09-03 11:42
@rlucassen2 

You are basically describing an import feature using m3u as the exchange format. In this regard the feature request is a duplicate of #126. I would like to have the feature as well, but I am not going to implement this in the near future, since I don't have much free time at the moment. But the issue is mentioned in the list of features that could be implemented by a project contributor ([Previous discussions and feature requests](https://github.com/y20k/transistor/issues/48)).

Thanks for the suggestion in any case :+1: 

PS: The m3u you mentioned (http://radio.xaq.nl/m3u/speech.m3u) imports a spanish language radio station on my phone.

**Closed by y20k** 2020-09-03 11:42 UTC
Labels: enhancement

**Comment by quite** [comment] 2020-12-11 08:16
This would be a really practical way of keeping a personal m3u of stations, and letting Transistor (and other programs) pick it up. For me, it would replace the need for import/export, and would actually be more convenient.
