### ISSUE TITLE
Transistor streams though playback is stopped

### ISSUE THREAD

**Issue by Spielmops** [y20k/transistor#362] opened 2021-08-01 16:34 UTC
Transistor continues to stream even though playback has stopped. I can see this in the data speed meter in the status bar. The data rate goes to zero immediately when I close the app manually.

LineageOS 18.1 on Raspberry Pi 4
Transistor 4.0.14

Spielmops

**Comment by y20k** [comment] 2021-08-02 10:29
Hi @Spielmops 

my app on a Raspi. That's nice :-)

This bug will probably/hopefully be fixed with [v4.0.15](https://github.com/y20k/transistor/releases/tag/v4.0.15). It was reported earlier here: #354 - please report back if the issue is solved when the update arrives on your Raspi.

**Comment by Spielmops** [comment] 2021-08-02 15:30
Only for your interest: https://konstakang.com/devices/rpi4/LineageOS18/
Works good with Pi 4, I'm building a headunit with 9''-touchscreen.
Currently searching for a Internet-radio-app with big fonts, so I can read the radio-info while driving.

Spielmops

**Comment by Spielmops** [comment] 2021-08-06 07:47
The app is ok now, Transistor stops streaming after stop of playback.

Spielmops

**Closed** 2021-08-06 07:47 UTC
Labels: bug
