### ISSUE TITLE
Change icon crashes the app

### ISSUE THREAD

**Issue by edgato** [y20k/transistor#109] opened 2016-10-23 03:04 UTC
Echa time I try to change the icon of a radio the app crashes, so I am not able to use this function

**Comment by edgato** [comment] 2016-10-23 03:07
Sorry *change icon
*Each time

**Comment by y20k** [comment] 2016-10-23 18:27
Hi there,

Thanks for reporting this bug. I will try to fix it. Since the feature works fine for me on my test device and in emulators your situation may be some kind of edge case. I need some information about your phone.

- manufacturer and exact model
- Android Version / custom ROM / root access?
- does the device have a sd card slot - and do you have a working sd card in that slot / Is the sd card "full"
- did you grant Transistor the rights to read pictures from external storage (permission "Storage")

Best regards and sorry that you are not able to change icons right now.

**Comment by edgato** [comment] 2016-10-23 19:15
Hi, this is the info 
- Model: Motorola Moto G XT1032
-Android Version: 5.1 stock, No Root
- SD slot: this Model do not have a slot
- Transistor has the permission to read storage

In both cases having and not having an icon the app crashes when I touch the option, I dont reach the image picker, It crashes when I select change icon in the options menu, also I am using the version in spanish but I dont know if that is important.


thank you.

**Comment by y20k** [comment] 2016-10-24 14:31
Okay. Thank you. I will try to replicate the bug with an emulator and report back here.

**Comment by y20k** [comment] 2016-10-26 12:55
Hi @edgato , 

I am sorry but I could not reproduce the error using an emulated phone running Android 5.1. The code that called the image picker had a few inconsistencies that I cleaned up (see [commit](https://github.com/y20k/transistor/commit/a7a18c263732d9154a12cc4bbc4a1cf25f7799e9)). So there is a slight chance that the next version ([v2.1.6](https://github.com/y20k/transistor/releases/tag/v2.1.6)) might help you.

If not, I am not sure what to do: Depending on the amount of time/effort you want to spent you could try to capture a crashreport using [logcat](https://developer.android.com/studio/command-line/logcat.html) and send it to me. Alternatively there is always the option to place a 300x300 pixel PNG manually into the folder: /Android/data/org.y20k.transistor/files/Collection

Best regards

**Comment by y20k** [comment] 2016-12-05 08:43
I am closing this issue, because I could not figure out what went wrong. Feel free to re-open, if you have additional information that might help me to find the cause.

**Closed by y20k** 2016-12-05 08:43 UTC
