### ISSUE TITLE
Feature: autostart a station + auto reconnect

### ISSUE THREAD

**Issue by tiborroald** [y20k/transistor#256] opened 2020-05-08 09:45 UTC
I would want, please, to have the app to:
 - to connect automatically at startup to a predefined stream (radio station)
 - to have an option to indifenitelly reconnect if network is temporarly down

**Comment by y20k** [comment] 2020-05-08 18:46
Hi there,

I am not planning to implement an autostart feature. Transistor is a very lean app and I want to keep it simple. But. The app lets you create shortcuts for radio station on your home screen. That should do the trick for you.

And your second request: Can you describe the problem? Does the apps state switch back from "playing" to "stopped" during network outages? I am using the app only at home, where I have a stable network connection.

**Comment by tiborroald** [comment] 2020-05-11 10:42
Hello y20k,

- I'm using "Auto Start" (AutoStart No root_v2.2.apk) app that only start apps and NOT shortcuts. That's the reason to add that option.  If you help me a bit how you
setup up your build environment ... I may start to contribute



- The network drops it's fact of life, you know. If you add reconnect feature then it will behave more like a real radio. Even if transmission stop, the radio still "listen" and make static noise, but will not shutdown/close automatically.

**Comment by tiborroald** [comment] 2020-05-11 10:55
I've searched a bit for other autostart apps and no one is starting home screen shortcuts

**Comment by y20k** [comment] 2020-05-11 12:03
There might be another way. If the autostart app supports Intents and Intent Extras you should be able to start Transistor and pass the station information via Intent.

You can start the app using the following parameters
- Intent Action: `org.y20k.transistor.action.START_PLAYER_SERVICE`
- Intent Extra: `START_LAST_PLAYED_STATION` = true

If you want to start a certain station, it becomes **more** complicated
- get station `uuid` from the file `/Android/data/org.y20k.transistorone/files/collection/collection.json`
- start PlayerServiceStarterActivity (and not MainActivity) using the following parameters
- Intent Action: `org.y20k.transistor.action.START_PLAYER_SERVICE`
- Intent Extra: `STATION_UUID` = the-uuid-from-collection.json

I am interested if that is helpful for your purpose.

**Comment by y20k** [comment] 2020-05-11 12:43
There is kind of documentation for older versions of Transistor over in the [Wiki](https://github.com/y20k/transistor/wiki).

I will need to update this for the upcoming version 4. The adb-commands for version 4 are / will be:

**Start last station**
`./adb shell am start -n "org.y20k.transistor/org.y20k.transistor.MainActivity" -a "org.y20k.transistor.action.START_PLAYER_SERVICE" --ez "START_LAST_PLAYED_STATION" true`


**Start a certain station**
`./adb shell am start -n "org.y20k.transistor/org.y20k.transistor.MainActivity" -a "org.y20k.transistor.action.START_PLAYER_SERVICE" --es "STATION_UUID" "the-uuid-from-collection.json"`

**Start a station in background**
`./adb shell am start -n "org.y20k.transistor/org.y20k.transistor.PlayerServiceStarterActivity" -a "org.y20k.transistor.action.START_PLAYER_SERVICE" --es "STATION_UUID" "the-uuid-from-collection.json"`

**Comment by tiborroald** [comment] 2020-05-11 12:58
The "Auto Start" app has no idea of intent. When you're offered to select what to start it only shows apps and nothing more.

At first we may add in core/Station.kt:
data class Station (@Expose val uuid: String = UUID.randomUUID().toString(),
                    @Expose var autostart: Boolean = false,
                    @Expose var starred: Boolean = false,

    fun deepCopy(): Station {
        return Station(uuid = uuid,
                       autostart = autostart,
                       starred = starred,

**Comment by tiborroald** [comment] 2020-05-11 12:59
And do similar copy&paste function for:
   private fun setStarredIcon(stationViewHolder: StationViewHolder, station: Station) {
to
   private fun setAutostartIcon(stationViewHolder: StationViewHolder, station: Station) {

**Comment by tiborroald** [comment] 2020-05-11 13:02
From UI programming perspective I think will not be to hard. 
Yes, I know all station can be potentially "autostartable" so the option should be like a radiobutton. But, as an ugly hack, you may start first one found.

Because I don't know Kotlin, it will be hard for me to write glue logic to
modify Transistor startup code that will allow selected station autostart.

**Comment by tiborroald** [comment] 2020-05-11 13:05
Ah, I found in your patch https://github.com/y20k/transistor/commit/6b605f9861c1c8fa58cef0891fd10bb30261906b

The MediaControllerCompat.getMediaController(activity as Activity).transportControls.playFromMediaId(uuid, null) I think just can be added
at startup after checking what is the first station in collection with autostart == True,
then get uuid, then start the playFromMediaId()

Is that a manageable code?

**Comment by y20k** [comment] 2020-05-11 13:53
Sorry to disappoint. But I will probably not add a special autostart option in the UI as said earlier. It is too much of a special interest feature. I think you need to check out apps like [Tasker](https://tasker.joaoapps.com/) (or free alternatives) that support starting apps via Intent. Again sorry.

I intent to work on the second feature request though: Improve the reconnect behavior.

**Comment by tiborroald** [comment] 2020-05-11 14:06
OK. Good with Tasker. Forgot about it.

**Comment by tiborroald** [comment] 2020-05-11 14:36
Is the STATION_UUID or EXTRA_STATION_UUID?

Tasker will start the Player, but not play the stream:


            if (intent.hasExtra(Keys.EXTRA_STATION_UUID)) {
                // start station with uuid from intent
                startIntent.putExtra(Keys.EXTRA_STATION_UUID, intent.getStringExtra(Keys.EXTRA_STATION_UUID))
            }

**Comment by y20k** [comment] 2020-05-11 14:52
`STATION_UUID` :+1:

**Comment by tiborroald** [comment] 2020-05-11 15:13
Thanks!
In Tasker I have DATA field. But I cannot find any formating rule.
Seems to be a free form field. 
Is Ok the following format?

STATION_UUID=ceb453b6-b568-4f94-a894-965c1a90b7c6

**Comment by y20k** [comment] 2020-05-11 15:34
I actually haven't used Tasker in a while. I found two links that might help you getting started.

https://forum.xda-developers.com/showthread.php?t=2489449
https://tasker.joaoapps.com/userguide/en/intents.html
(STATION_UUID internally is a String-Extra)

**Comment by tiborroald** [comment] 2020-05-12 06:43
I tried to start from adb:
adb shell am start "org.y20k.transistor/org.y20k.transistor.PlayerServiceStarterActivity" -a "org.y20k.transistor.action.START_PLAYER_SERVICE" --es "STATION_UUID" "bc0b4dbd-67a1-4754-897b-68f90731733c"

But is not working. 

Start, but not play.

... ,"uuid":"bc0b4dbd-67a1-4754-897b-68f90731733c"}],"version":0

**Comment by tiborroald** [comment] 2020-05-12 07:03
Anyway the workflow is awkard. If you want to use Tasker to automate:
1. Add station
2. Connect you device to USB
3. Go to shell with adb
4. cat the collection
5. Search by hand or with grep or better copy & paste to search in a decent editor with JSON formatter
6. Write down to paper the UUID
7. Manually enter it in Tasker... and hope for no mistake in typing.

I would suggest:
 - make it a label that can be copied in Transistor and pasted in Tasker

Programmer note: UUIDs are for machines not for humans. To use it for app user, use a shorted SHA1 hash. Note that git log --oneline is showing only first 8 chars and rarely clash.

**Comment by y20k** [comment] 2020-05-12 19:40
> the workflow is awkard

I agree. The old workflow (as seen in the [Wiki](https://github.com/y20k/transistor/wiki)) is easier. You just needed the stream URL, which you can copy to the clipboard. I probably should add this feature, too.

**Comment by y20k** [comment] 2020-05-13 14:57
I enabled starting playback of a station via a `STREAM_URI` Extra.

**Usage:**
`./adb shell am start -n "org.y20k.transistor/org.y20k.transistor.MainActivity" -a "org.y20k.transistor.action.START_PLAYER_SERVICE" --es "STREAM_URI" "http://yourstationstre.am"`


Check out the latest [APK](https://github.com/y20k/transistor/issues/251#issuecomment-628044176), if you are interested.

**Comment by tiborroald** [comment] 2020-05-14 07:50
I have my build locally for API23. Thanks!  
Updated and recompiled. But... it's not working. Start the player, but not the stream.

I use something like:
adb shell am start "org.y20k.transistor/org.y20k.transistor.PlayerServiceStarterActivity" -a "org.y20k.transistor.action.START_PLAYER_SERVICE" --es "STREAM_URI" "https://myhost.mydomain:8000/stream64"

How can I enable logging for the app?
I have adb logcat is just showing all activity on Android and but only standard Transistor 
app start/stop.

**Comment by tiborroald** [comment] 2020-05-14 07:59
Working! I was not pay attention. Copy&paste error. Used PlayerServiceStarterActivity instead of MainActivity

**Comment by tiborroald** [comment] 2020-05-14 09:09
It works from adb, but from Tasker Send Intent.

I had a look in AndroidManifest.xml and seems that MainActivity will not receive org.y20k.transistor.action.START_PLAYER_SERVICE.

Am I wrong?

**Comment by y20k** [comment] 2020-05-14 09:26
nope. you are correct. the entry was missing. we are finally getting here. thank you!!!

**Comment by tiborroald** [comment] 2020-05-14 09:44
I've ran a git pull but I don't see your change

**Comment by tiborroald** [comment] 2020-05-14 09:51
I see it. Recompiled. But not working!
Test:
1. Stopped the stream
2. Switched to Tasker and launched Send Intent
3. Transistor was brought to front, but stream was not started.

Note: If Transistor is removed from tasks, then when started, the play will start

**Comment by y20k** [comment] 2020-05-14 09:54
I did not test this issue using Tasker. the adb command works for me though. Same for you?

**Comment by tiborroald** [comment] 2020-05-14 09:56
Even with adb will not work. Probably an error in code logic.

**Comment by y20k** [comment] 2020-05-14 09:59
`adb shell am start -n "org.y20k.transistor/org.y20k.transistor.MainActivity" -a "org.y20k.transistor.action.START_PLAYER_SERVICE" --es "STREAM_URI" "https://xyz"`
is the command I am using. And it starts playback regardless if Transistor is in the background, in the background or not active at all.

**Comment by tiborroald** [comment] 2020-05-14 10:03
How can I activate logging mode for app? I want to put some message to track activities

**Comment by y20k** [comment] 2020-05-14 10:12
I am using the LogHelper class to add log entries ([example](https://github.com/y20k/transistor/blob/1373e62d0a2117a4646c898b2bb01c35ca82cb41/app/src/main/java/org/y20k/transistor/Transistor.kt#L44)). Log entries can be viewed via logcat ([1](https://developer.android.com/studio/debug/am-logcat)) ([2](https://developer.android.com/studio/command-line/logcat)) afterwards.

**Comment by tiborroald** [comment] 2020-05-14 12:18
After tablet reboot, the Sent Intent will not work.

05-14 15:09:50.713   791  1598 I ActivityManager: START u0 {act=org.y20k.transistor.action.START_PLAYER_SERVICE flg=0x30800004 cmp=org.y20k.transistor/.MainActivity (has extras)} from uid 10110 from pid 1889 on display 0
05-14 15:09:51.148  2490  2490 D transistor_PlayerService: Starting Playback. Station: https://myhost.mydomain:8000/stream64.
05-14 15:09:51.159  2490  2490 E transistor_PlayerService: NOT playWhenReady AND OTHER
05-14 15:09:51.210  2490  2490 E transistor_PlayerService: playWhenReady AND OTHER (BUFFERING?)
05-14 15:09:51.320   791   801 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.ads.identifier.service.START pkg=com.google.android.gms } U=0: not found
05-14 15:09:51.963  2490  2490 V transistor_PlayerService: PlayerService - reload collection after broadcast received.
05-14 15:09:51.963  2490  2490 V transistor_PlayerService: Loading collection of stations from storage

I had a look in the code. The fun onStart() is called, but not the one that start the player

**Comment by tiborroald** [comment] 2020-05-14 12:49
After the Transistor app is started, the intent is handled by handleStartIntent() in PlayerFragment.

But the when() { ... } will not have something that will handle Keys.ACTION_START_PLAYER_SERVICE -> handleStartPlayer()

**Comment by y20k** [comment] 2020-05-14 12:51
I am looking into it. I now can reproduce the problem.

**Comment by y20k** [comment] 2020-05-14 13:07
Mmmh. Actually it turned out that I still can not reproduce the problem :-/ I thought I could ... then I found out that I tried to start a station that was not exactly the station in my station list (slightly different stream URL).

The command
`adb shell am start -n "org.y20k.transistor/org.y20k.transistor.MainActivity" -a "org.y20k.transistor.action.START_PLAYER_SERVICE" --es "STREAM_URI" "https://xyz"`
works for me also when the device is freshly restarted.

**Comment by tiborroald** [comment] 2020-05-14 13:09
Here is an logcat.
https://pastebin.com/piai6Rc0

**Comment by tiborroald** [comment] 2020-05-14 13:12
And this is modified code to handle my extended logging: https://pastebin.com/g5K6LVWX

**Comment by y20k** [comment] 2020-05-14 13:27
Can you put the following in the else branch

`LogHelper.d(TAG, "Number of intent extras ${intent.extras?.size()}")`

Do you have more than 0 Extras?

**Comment by tiborroald** [comment] 2020-05-14 14:03
Yes.
05-14 17:02:19.672  4189  4189 V transistor_PreferencesHelper: IDs of active downloads: zero
05-14 17:02:19.742  4189  4189 I transistor_PlayerFragment: THIS_IS_MY_MARKER: handleStartIntent
05-14 17:02:19.742  4189  4189 I transistor_PlayerFragment: THIS_IS_MY_MARKER: handleStartPlayer before
05-14 17:02:19.742  4189  4189 D transistor_PlayerFragment: THIS_IS_MY_MARKER: Number of intent extras 1
05-14 17:02:19.742  4189  4189 I transistor_PlayerFragment: THIS_IS_MY_MARKER: handleStartPlayer after
05-14 17:02:19.743  4189  4189 D transistor_PlayerFragment: Session ready. Update UI.



The modified code is:
        if ((activity as Activity).intent.action != null) {
            val i = (activity as Activity).intent
            LogHelper.i(TAG, "THIS_IS_MY_MARKER: handleStartPlayer before")
            when ((activity as Activity).intent.action) {
                Keys.ACTION_SHOW_PLAYER -> handleShowPlayer()
                Intent.ACTION_VIEW -> handleViewIntent()
                Keys.ACTION_START_PLAYER_SERVICE -> handleStartPlayer()
                else -> LogHelper.d(TAG, "THIS_IS_MY_MARKER: Number of intent extras ${i.extras?.size()}")            
            }
            LogHelper.i(TAG, "THIS_IS_MY_MARKER: handleStartPlayer after")
        }

**Comment by y20k** [comment] 2020-05-14 14:06
Okay. I think I misunderstood you. Sorry. Does `handleStartPlayer` get called at all?

**Comment by tiborroald** [comment] 2020-05-14 14:16
Nope. That's what is strage. I think the code is following a different code path.

**Comment by y20k** [comment] 2020-05-14 14:25
Then the app gets started with a different intent action than `org.y20k.transistor.action.START_PLAYER_SERVICE`.

You may want try to find that out using this modified method.

```
    private fun handleStartIntent() {
        if ((activity as Activity).intent.action != null) {
            LogHelper.d(TAG, "Intent action = ${(activity as Activity).intent.action.toString()}")
            when ((activity as Activity).intent.action) {
                Keys.ACTION_SHOW_PLAYER -> handleShowPlayer()
                Intent.ACTION_VIEW -> handleViewIntent()
                Keys.ACTION_START_PLAYER_SERVICE -> handleStartPlayer()
                else -> LogHelper.d(TAG, "None of the three :-/")
            }
        }
        // clear intent action to prevent double calls
        (activity as Activity).intent.action = ""
    }
```

**Comment by tiborroald** [comment] 2020-05-14 14:37
Very strange!

https://pastebin.com/XJaA90cC

**Comment by y20k** [comment] 2020-05-14 14:39
Strange indeed. I hope not to sound rude. This whole issue is a bit of time sink for me - and for you probably, too. 42 comments so far. I think we need to close it soon. There must be other radio players that offer a more convenient way for what you want

**Comment by tiborroald** [comment] 2020-05-14 14:55
Sure, no problem. I'll continue myself. I'll keep you in the loop if I'll found anything.

**Closed** 2020-05-14 14:56 UTC
Labels: enhancement
