### ISSUE TITLE
[issue] station currently playing

### ISSUE THREAD

**Issue by ralxxx** [y20k/transistor#166] opened 2018-02-11 11:42 UTC
There's an issue with the green light, indicating the radio stream currently playing. 
When I start Transistor (3.0.2), the app still indicates with a green dot the radio stream that I used last time. 
When I chose another stream for listening, I have 2 green dots at the same time.

**Comment by y20k** [comment] 2018-02-12 13:24
Hi. I cannot reproduce this issue, but I have an idea. The behavior you report may happen, when the app crashes while playing music, or when the app is killed by the system while playing music. Is that the case on your device?

**Comment by ralxxx** [comment] 2018-02-12 13:53
Not necessarily crashing.... 
The issue does not happen when I did not use the app for a certain while. 
But when I start using the app, I close it and restart it right away, then I still have the green light from the previous session on (even though the stream is not playing). When I select another station, then I have 2 green dots. Does that help?

**Comment by ralxxx** [comment] 2018-02-12 14:04
To reproduce this issue, a stream must be playing when I close the app. 

AND: When I reopen the app after having clused it (while playing), the play button pretends to play a stream, I can click on it (long press or clicking the play button), then the green light disappears where the button is still in playing mode). The play button only start reacting when I chose another stream first (long press or clicking the play button). 
Still, when I try to select the initial stream (long press or clicking the play button) Transistor seems not to react.

**Comment by y20k** [comment] 2018-02-12 14:20
> a stream must be playing when I close the app.

What do you mean by closing? 
App switcher and swiping away the app? When I do that only the UI gets closed the music continues to play.

**Comment by ralxxx** [comment] 2018-02-12 14:29
Closing for me means indeed: App switcher > swiping away the app.
For me: the app is closing and the current stream is stopping.

My system: I use Android 7.1.2/MIUI9.2

**Comment by y20k** [comment] 2018-02-12 15:42
Okay. Thanks. I think I have a way to fix that. Please wait for the next version of the app.

**Comment by y20k** [comment] 2018-02-14 12:53
[v3.0.3](https://github.com/y20k/transistor/releases/tag/v3.0.3) is out (on GitHub and Google Play and soon on F-Droid). The app now should correctly "remember" / "sense" if it is playing back music.

**Closed by y20k** 2018-02-14 12:53 UTC
Labels: bug
