### ISSUE TITLE
Battery usage

### ISSUE THREAD

**Issue by idata** [y20k/transistor#83] opened 2016-04-28 12:26 UTC
Bonjour, greetings. I really love and appreciate your transistor application, thanks for the job you done to it. I want to signal to you a problem appears since the last update, when now we have the name of the track and artist when transistor is playing. With nexus 5 under the last marshmallow update, one hour of playing with transistor and 15/25% of m'y battery used by the application. 2 hours, more of 40%. Then i stoped to use your application since the last update when i cannot charge m'y smartphone. 
Thanks for reading Christian.

**Comment by y20k** [comment] 2016-04-28 17:29
Hey. 

Thank you for opening this issue. 

I did not measure battery usage before. I am still on vacation. I will look into it on Saturday. 

@pelya : Do you have an idea what may be the cause for the battery drain?

Best regards

**Comment by pelya** [comment] 2016-04-28 17:45
The ShoutcastProxyConnection class does impact CPU usage, but I did not
expect it to be that awful. I think we can measure CPU usage per thread
using DDMS.

How much better was the previous release?

**Comment by y20k** [comment] 2016-04-28 19:43
For anyone who wants to test the potential battery impact: 

I did compile a signed APK of v2.0.1 without the metadata extraction.

Official v2.0.1
https://github.com/y20k/transistor/releases/download/v2.0.1/transistor-app-release-2.0.1.apk

Test Version of v2.0.1
https://www.dropbox.com/s/s03he0o9lrn7gkg/transistor-app-test-nometadata-2.0.1.apk?dl=0

(And now back to vacation ;-) )

**Comment by idata** [comment] 2016-04-30 21:19
Thanks for this apk. I'll try it in a few jours and i'll return m'y comments. Have à nice vacation. :)

**Comment by y20k** [comment] 2016-06-06 14:06
Can I close this issue?

I do not have any battery issues since the introduction of the metadata display. 

If someone has data on this or an idea how to improve battery performance, please reopen this - or start a new bug report.

Best regards

**Closed** 2016-06-09 19:37 UTC
